### ISSUE TITLE
verify your email page needs overhaul.

### ISSUE THREAD

**Issue by bhanuvrat** [essentiasoftserv/vachan#79]
The page that shows up after a user registers is misconfigured.
It needs css updates. 
The message should be loud and center.
The message should ask the user to check the inbox of the email account they just registered with before proceeding.

**Comment by yryuvraj** [comment]
Reminder to close this issue! 
For better clarity.

**Comment by bind-ritu1211** [comment]
Updated CSS for the verify your email page has been merged and deplyed.
