### ISSUE TITLE
Issues [June Week 1]

### ISSUE THREAD

**Issue by nupuragrahari** [essentiasoftserv/vachan#89]
- [x] The New person feature on the [listing page](https://vaaak.com/people) 
    - [x] accepts numbers for name as inputs as well
    - [x] accepts single letter for name
- [x] New person error "has already been taken" on adding existing email needs to be updated to "Email has already been taken"
- [x] New person creation success message does not disappear automatically
- [x] We need place holders for input boxes everywhere
- [x] [Adding sender profile](https://vaaak.com/sender-profiles/new) module
    - [ ] Validation missing for all fields
    - [x] SMTP password might need encryption
    - [x] Errors on saving the form for the first 3 fields
- [x] [Lists](https://vaaak.com/lists/3)
    - [x] No way to add people to lists
    - [x] The text "ee" floating up at top left
    - [ ] The edit list button should not edit the name of the list. It should edit people in the list 
- [x] [Campaign](https://vaaak.com/campaigns/new) 
    - [ ] In case there are No sender profiles the form should not show a drop down
    - [ ] Create new campaign feature not working
    - [ ] List in the drop down should not work if the list does not have people added to it
    - [ ] Run campaign feature not working

**Comment by Sarlin-7757** [comment]
Bugfix: The text "ee" floating at top left -> pr raised

**Comment by Sarlin-7757** [comment]
Bugfix: No way to add people to lists -> pr merged

**Comment by Sarlin-7757** [comment]
Bugfix: No way to add people to lists -> pr merged #97

**Comment by nupuragrahari** [comment]
Add Sender profile feature works. Fix has been merged and deployed.

**Comment by nupuragrahari** [comment]
@bind-ritu1211 working on List view and bug fix for adding people to lists

**Comment by nupuragrahari** [comment]
@Sarlin-7757 to add placeholders to form fields

**Comment by nupuragrahari** [comment]
New person error "has already been taken" on adding existing email needs to be updated to "Email has already been taken"

fixed by @yryuvraj  PR raised-103

**Comment by nupuragrahari** [comment]
@yryuvraj to pick up validations for sender profile form

**Comment by nupuragrahari** [comment]
@Jixiee to update side bar icons

**Comment by bhanuvrat** [comment]
Encryption will also need decryption.
The application needs the password in plain text to authenticate against an email server.

**Comment by Sarlin-7757** [comment]
@bhanuvrat , we can skip this for now ?
